### ISSUE TITLE
[RC5.1] Default temp targets not working correctly in mmol/l

### ISSUE THREAD

**Issue by roppenheimer** [MilosKozak/AndroidAPS#1289] opened 2018-08-01 18:42 UTC
If you enter a value for a default temp target then it is interpreted as mg/dl even if the app is using mmol/l. This causes a target out of hard limits error when the TT is used.

Reporting bugs
--------------
- Note the precise time the problem occurred and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by jotomo** [comment] 2018-08-01 20:57
Duplicate of https://github.com/MilosKozak/AndroidAPS/issues/1254, fix is in `dev`

**Closed** 2018-08-01 21:13 UTC
