### ISSUE TITLE
[2.4-dev] Restart caused by signature verifier

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#1911] opened 2019-07-29 12:06 UTC
AAPS is restarting from time to time.
Logcat:
```
2019-07-29 13:58:20.434 12577-12577/info.nightscout.androidaps E/PROFILE: [main] [ProfileFunctions.getProfile():141]: getProfile at the end: returning null
2019-07-29 13:58:20.477 12577-12577/info.nightscout.androidaps E/PROFILE: [main] [ProfileFunctions.getProfile():141]: getProfile at the end: returning null
2019-07-29 13:58:20.494 12577-12577/info.nightscout.androidaps E/PROFILE: [main] [ProfileFunctions.getProfile():141]: getProfile at the end: returning null
2019-07-29 13:58:20.790 12577-12632/info.nightscout.androidaps E/CORE: [Thread-14] [SignatureVerifier.lambda$onStart$0$SignatureVerifier():79]: Could not download revoked certs
    java.io.FileNotFoundException: https://raw.githubusercontent.com/MilosKozak/AndroidAPS/master/app/src/main/assets/revoked_certs.txt
    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251) ~[na:0.0]
    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210) ~[na:0.0]
    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.downloadRevokedCerts(SignatureVerifier.java:167) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.downloadAndSaveRevokedCerts(SignatureVerifier.java:139) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.lambda$onStart$0$SignatureVerifier(SignatureVerifier.java:77) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.general.signatureVerifier.-$$Lambda$SignatureVerifier$hbSmvbIXGw4HHSMj4qluBy-6pf0.run(Unknown Source:2) ~[na:0.0]
    	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```
If I proof the URL for the revoked certs I get a 404.

**Comment by swissalpine** [comment] 2019-07-29 12:25
Changing "master" against "dev" in URL will fix the restarts - but AAPS shouldn't crash if the cert isn't availbale.

**Comment by swissalpine** [comment] 2019-07-29 13:19
If I  change in the URL "master" to "dev", the app founds the file but have the next exception:
```
2019-07-29 15:10:21.205 13445-13445/info.nightscout.androidaps E/RecyclerView: No adapter attached; skipping layout
2019-07-29 15:10:23.670 13565-13565/info.nightscout.androidaps E/PROFILE: [main] [ProfileFunctions.getProfile():141]: getProfile at the end: returning null
2019-07-29 15:10:23.722 13565-13565/info.nightscout.androidaps E/PROFILE: [main] [ProfileFunctions.getProfile():141]: getProfile at the end: returning null
2019-07-29 15:10:23.746 13565-13565/info.nightscout.androidaps E/PROFILE: [main] [ProfileFunctions.getProfile():141]: getProfile at the end: returning null
2019-07-29 15:10:24.057 13565-13612/info.nightscout.androidaps E/AndroidRuntime: FATAL EXCEPTION: Thread-14
    Process: info.nightscout.androidaps, PID: 13565
    org.spongycastle.util.encoders.DecoderException: exception decoding Hex string: invalid characters encountered in Hex string
        at org.spongycastle.util.encoders.Hex.decode(Hex.java:132)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.parseRevokedCertsFile(SignatureVerifier.java:199)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.loadLocalRevokedCerts(SignatureVerifier.java:152)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.lambda$onStart$0$SignatureVerifier(SignatureVerifier.java:74)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.-$$Lambda$SignatureVerifier$hbSmvbIXGw4HHSMj4qluBy-6pf0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: invalid characters encountered in Hex string
        at org.spongycastle.util.encoders.HexEncoder.decode(HexEncoder.java:180)
        at org.spongycastle.util.encoders.Hex.decode(Hex.java:128)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.parseRevokedCertsFile(SignatureVerifier.java:199) 
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.loadLocalRevokedCerts(SignatureVerifier.java:152) 
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.lambda$onStart$0$SignatureVerifier(SignatureVerifier.java:74) 
        at info.nightscout.androidaps.plugins.general.signatureVerifier.-$$Lambda$SignatureVerifier$hbSmvbIXGw4HHSMj4qluBy-6pf0.run(Unknown Source:2) 
        at java.lang.Thread.run(Thread.java:764) 
2019-07-29 15:10:34.112 13647-13647/info.nightscout.androidaps E/PROFILE: [main] [ProfileFunctions.getProfile():141]: getProfile at the end: returning null
2019-07-29 15:10:34.499 13647-13694/? E/AndroidRuntime: FATAL EXCEPTION: Thread-14
    Process: info.nightscout.androidaps, PID: 13647
    org.spongycastle.util.encoders.DecoderException: exception decoding Hex string: invalid characters encountered in Hex string
        at org.spongycastle.util.encoders.Hex.decode(Hex.java:132)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.parseRevokedCertsFile(SignatureVerifier.java:199)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.loadLocalRevokedCerts(SignatureVerifier.java:152)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.lambda$onStart$0$SignatureVerifier(SignatureVerifier.java:74)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.-$$Lambda$SignatureVerifier$hbSmvbIXGw4HHSMj4qluBy-6pf0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: invalid characters encountered in Hex string
        at org.spongycastle.util.encoders.HexEncoder.decode(HexEncoder.java:180)
        at org.spongycastle.util.encoders.Hex.decode(Hex.java:128)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.parseRevokedCertsFile(SignatureVerifier.java:199) 
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.loadLocalRevokedCerts(SignatureVerifier.java:152) 
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.lambda$onStart$0$SignatureVerifier(SignatureVerifier.java:74) 
        at info.nightscout.androidaps.plugins.general.signatureVerifier.-$$Lambda$SignatureVerifier$hbSmvbIXGw4HHSMj4qluBy-6pf0.run(Unknown Source:2) 
        at java.lang.Thread.run(Thread.java:764) 
2019-07-29 15:10:37.083 13715-13761/? E/AndroidRuntime: FATAL EXCEPTION: Thread-14
    Process: info.nightscout.androidaps, PID: 13715
    org.spongycastle.util.encoders.DecoderException: exception decoding Hex string: invalid characters encountered in Hex string
        at org.spongycastle.util.encoders.Hex.decode(Hex.java:132)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.parseRevokedCertsFile(SignatureVerifier.java:199)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.loadLocalRevokedCerts(SignatureVerifier.java:152)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.lambda$onStart$0$SignatureVerifier(SignatureVerifier.java:74)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.-$$Lambda$SignatureVerifier$hbSmvbIXGw4HHSMj4qluBy-6pf0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: invalid characters encountered in Hex string
        at org.spongycastle.util.encoders.HexEncoder.decode(HexEncoder.java:180)
        at org.spongycastle.util.encoders.Hex.decode(Hex.java:128)
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.parseRevokedCertsFile(SignatureVerifier.java:199) 
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.loadLocalRevokedCerts(SignatureVerifier.java:152) 
        at info.nightscout.androidaps.plugins.general.signatureVerifier.SignatureVerifier.lambda$onStart$0$SignatureVerifier(SignatureVerifier.java:74) 
        at info.nightscout.androidaps.plugins.general.signatureVerifier.-$$Lambda$SignatureVerifier$hbSmvbIXGw4HHSMj4qluBy-6pf0.run(Unknown Source:2) 
        at java.lang.Thread.run(Thread.java:764) 
```
It seems that there are invalid characters in revoked_certs.txt.

**Comment by MilosKozak** [comment] 2019-07-29 18:50
First log is OK, code is not merged to master yet

**Comment by MilosKozak** [comment] 2019-07-29 18:52
i changed URL to https://raw.githubusercontent.com/MilosKozak/AndroidAPS/dev/app/src/main/assets/revoked_certs.txt
but it works as it should.

**Comment by swissalpine** [comment] 2019-07-29 18:56
If I disable signature verifier in MainApp.java I see another restart every 10 minutes.
Logcat:
```
2019-07-29 20:38:17.248 1199-1282/system_process E/InputDispatcher: channel 'c68bc32 info.nightscout.androidaps/info.nightscout.androidaps.activities.SingleFragmentActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-07-29 20:38:17.250 1199-1282/system_process E/InputDispatcher: channel 'f170170 info.nightscout.androidaps/info.nightscout.androidaps.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```
If I disable tidepool no restarts happens. Log excerpt of the restart:
```
20:38:15.828 [pool-1-thread-1] D/DATABASE: [DatabaseHelper$1PostRunnable.run():414]: Firing EventNewBg
20:38:15.836 [RxCachedThreadScheduler-8] D/TIDEPOOL: [UploadChunk.get():40]: Syncing data between: 7/16/19 03:33PM -> 7/23/19 03:33PM
20:38:15.903 [Thread-114] D/DATABASE: [CareportalEvent.isEvent5minBack():142]: Found event for time: 7/28/19 11:09:00 PM Central European Summer Time CareportalEvent{date= 1564347956000, date= 7/28/19 11:05PM, isValid= true, _id= 1564347956188, eventType= Site Change, json= {"eventType":"Site Change","created_at":"2019-07-28T21:05:56Z","enteredBy":"AndroidAPS","notes":"","NSCLIENT_ID":1564347956188,"mills":1564347956000,"_id":1564347956188}}
20:38:15.940 [Thread-114] D/AUTOSENS: [Profiler.log():14]: >>> IobCobOref1Thread <<< executed in 109 miliseconds
20:38:16.655 [RxCachedThreadScheduler-8] D/TIDEPOOL: [EventTidepoolStatus.<init>():17]: New status: 1662 CGMs selected for upload
20:38:16.677 [RxCachedThreadScheduler-8] D/TIDEPOOL: [EventTidepoolStatus.<init>():17]: New status: 3 ProfileSwitches selected for upload
20:38:16.893 [RxCachedThreadScheduler-8] D/TIDEPOOL: [EventTidepoolStatus.<init>():17]: New status: Uploading
20:38:16.941 [Thread-115] D/APS: [LoopPlugin.invoke():274]: invoke from AutosenseCalculation for BgReading{date=1564425486000, date=Jul 29, 2019 8:38:06 PM, value=91.0, direction=Flat, raw=0.0}
20:38:16.942 [Thread-115] D/APS: [OpenAPSSMBPlugin.invoke():96]: invoke from AutosenseCalculation for BgReading{date=1564425486000, date=Jul 29, 2019 8:38:06 PM, value=91.0, direction=Flat, raw=0.0} tempBasalFallback: false
20:38:16.948 [Thread-115] D/DATATREATMENTS: [TreatmentsPlugin.getLastBolusTime():341]: Last bolus time: Jul 29, 2019 7:10:15 PM
20:38:16.949 [Thread-115] D/APS: [Profiler.log():14]: >>> getMealData() <<< executed in 2 miliseconds
20:38:18.772 [main] D/CORE: [MainApp.onCreate():137]: onCreate
20:38:18.802 [main] I/DATABASE: [DatabaseHelper.onCreate():124]: onCreate
20:38:19.098 [main] I/CORE: [MainApp.onCreate():155]: Version: 2.4-dev
20:38:19.100 [main] I/CORE: [MainApp.onCreate():156]: BuildVersion: eaec4a9b7-2019.07.29-18:27
20:38:19.102 [main] I/CORE: [MainApp.onCreate():157]: Remote: https://github.com/MilosKozak/AndroidAPS.git
20:38:19.207 [main] I/DATATREATMENTS: [TreatmentService.onCreate():108]: onCreate
20:38:19.219 [main] I/DATATREATMENTS: [TreatmentService.onUpgrade():135]: onUpgrade
20:38:19.230 [main] D/SMS: [SmsCommunicatorPlugin.processSettings():115]: Found allowed number: 
20:38:19.286 [main] D/CORE: [PluginBase.setPluginEnabled():146]: Starting: Overview
20:38:19.288 [main] D/CORE: [PluginBase.setPluginEnabled():146]: Starting: IobCobCalculator
```
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3443867/AndroidAPS.log)

**Comment by MilosKozak** [comment] 2019-07-29 19:02
tidepool is not in release ;)

**Comment by swissalpine** [comment] 2019-07-29 19:04
Yes, I know, but I thought it is helpful to search for problems. If you don't like it, I will stop it.

**Comment by MilosKozak** [comment] 2019-07-29 19:08
No sign of crash in logs. And i'm unable to reproduce it .... Did you create tidepool test account and trying to upload?

**Comment by swissalpine** [comment] 2019-07-29 19:10
I have a normal account. Probably this is my problem. No succesful login, but trying to upload ...

**Comment by MilosKozak** [comment] 2019-07-29 19:11
ok. i'll try it with wrong login

**Comment by MilosKozak** [comment] 2019-07-29 19:29
```
2019-07-29 21:23:36.270 23768-23768/info.nightscout.androidaps D/CORE: [main] [PluginBase.setPluginEnabled():146]: Starting: Tidepool
2019-07-29 21:28:17.475 23768-23847/info.nightscout.androidaps D/TIDEPOOL: [RxCachedThreadScheduler-1] [EventTidepoolStatus.<init>():17]: New status: Connecting
2019-07-29 21:28:17.506 23768-24322/info.nightscout.androidaps D/OkHttp: --> POST https://int-api.tidepool.org/auth/login
2019-07-29 21:28:17.506 23768-24322/info.nightscout.androidaps D/OkHttp: X-Tidepool-Client-Name: info.nightscout.androidapsinfo.nightscout.androidaps
2019-07-29 21:28:17.506 23768-24322/info.nightscout.androidaps D/OkHttp: X-Tidepool-Client-Version: 0.1.0
2019-07-29 21:28:17.507 23768-24322/info.nightscout.androidaps D/TIDEPOOL: [OkHttp https://int-api.tidepool.org/...] [InfoInterceptor.intercept():24]: Interceptor Body size: 0
2019-07-29 21:28:17.508 23768-24322/info.nightscout.androidaps D/TIDEPOOL: [OkHttp https://int-api.tidepool.org/...] [InfoInterceptor.intercept():27]: Interceptor Body: 
2019-07-29 21:28:18.623 23768-24322/info.nightscout.androidaps D/OkHttp: <-- 401 Unauthorized https://int-api.tidepool.org/auth/login (1115ms)
2019-07-29 21:28:18.623 23768-24322/info.nightscout.androidaps D/OkHttp: access-control-allow-headers: authorization, content-type, x-tidepool-session-token, x-tidepool-trace-request, x-tidepool-trace-session
2019-07-29 21:28:18.623 23768-24322/info.nightscout.androidaps D/OkHttp: access-control-expose-headers: x-tidepool-session-token, x-tidepool-trace-request, x-tidepool-trace-session
2019-07-29 21:28:18.638 23768-23768/info.nightscout.androidaps D/TIDEPOOL: [main] [TidepoolCallback.onResponse():22]: Login was not successful: 401 Unauthorized
2019-07-29 21:28:18.639 23768-23768/info.nightscout.androidaps D/TIDEPOOL: [main] [EventTidepoolStatus.<init>():17]: New status: Login was not successful: 401 Unauthorized
```
even with wrong login it works well

**Comment by MilosKozak** [comment] 2019-07-29 20:23
now it happended to me too. Tidepool plugin is guilty

**Comment by MilosKozak** [comment] 2019-07-29 21:21
fixed in dev

**Closed by MilosKozak** 2019-07-29 21:21 UTC

**Comment by swissalpine** [comment] 2019-07-30 14:56
:-)
