### ISSUE TITLE
2_6_5-Dev several issues in History Browser graphs

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2619] opened 2020-05-04 14:06 UTC
Scale issue on main graph (don't know if bg value are shown or not because completly out of range...)

Carbs are missing in 2nd graph
Nothing is shown in 3rd graph

(I have same curves selected on main tab and history browser...)

![Scale issue and missing information on history browser](https://user-images.githubusercontent.com/52934600/80974227-b8dfe500-8e20-11ea-8e28-02dbb762a244.jpg)

**Comment by Alamo04** [comment] 2020-05-04 15:34
Confirm that.

**Comment by dlvoy** [comment] 2020-05-05 21:07
Confirmed, additionally:
when navigating few (2) days back in history dialog **and going back to main screen** causes glitches with main screen display (invalid SGV, time since last reading, delta) & graphs:

<img src="https://user-images.githubusercontent.com/5094588/81115929-d0a09180-8f24-11ea-95b1-0be53207308c.jpg" width="300">

Going again in and out of history dialog resets main screen into up-to-date state

**Comment by MilosKozak** [comment] 2020-05-13 19:28
fixed in dev

**Closed by MilosKozak** 2020-05-13 19:28 UTC
