### ISSUE TITLE
Watchface Steampunk doesn't work on my Ticwatch pro

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2217] opened 2019-11-22 23:39 UTC
I don't know if it's specific to this watch (Ticwatch pro Wear OS 2.1) but Steampunk watchface doesn't work : 
No BG value
No Graph
No Delta
If i'm lucky I can have IOB and COB for a few minutes (3 or 4 min max)
Hour in center works just at the beginning and after 3 or 4 minutes, black screen with digital hour on the top of screen (ticwatch automatically switches to "simple" watchface)

Other watchfaces works well (I have not tested them all but AAPS v2 , AAPS, Circle, BigChart, Cockpit are OK...)

(Version: EB98CA765)

**Comment by Wolf1010** [comment] 2019-11-23 11:24
Hallo Pil,

try these settings in the Wear-Options!
![Settings_Wear](https://user-images.githubusercontent.com/34548300/69477901-2573a400-0dec-11ea-9094-4768a1944f2d.jpg)

**Comment by Wolf1010** [comment] 2019-11-23 11:26
...and wait for the next Value!

**Comment by dlvoy** [comment] 2019-11-23 13:38
I can confirm that on my watch (Huwawei Watch 2) it behaves the same
-  by default it toes not work
- turning off "Show detailed delta" fixes it, but turning it back on again will crash and restart watchface
- sending all data to watch again only refreshes contents partially, it need till next readout to be sent in incremental mode

I think this watch face need fixes for that - and additionally to support dim mode - since it currently make my watch go into crazy blinking state when attempting display all that white background when dimming

**Comment by dlvoy** [comment] 2019-11-23 13:43
I will look into it - as soon i get other watch changes (complication support PR #2203) tested and merged into upstream

**Comment by Philoul** [comment] 2019-11-25 09:27
Thanks for the workaround. It works...

**Comment by ShaggydogUK** [comment] 2019-11-27 09:50
I'm using a Huwei Watch 2 and have none of the problems listed with the Steampunk watchface.

**Closed** 2019-12-07 17:18 UTC

**Comment by Philoul** [comment] 2019-12-11 23:48
Bug corrected with https://github.com/MilosKozak/AndroidAPS/pull/2269
Problem with decimal character (bug if comma, ok if point)
