### ISSUE TITLE
NSClient and AAPS setting of Temporary Targets 2.6.0

### ISSUE THREAD

**Issue by erinlgrant** [MilosKozak/AndroidAPS#2515] opened 2020-03-18 13:53 UTC
Installed AAPS 2.6.0 on sons phone and NSClient 2.6.0 on my phone.
1)	In either app when a TT is set via custom it will disappear after a moment or two – around 5 seconds. In the treatment tab, under TT, you can see it set and then cancelled
2)	If you reload treatments from NS and return to the app – the TT comes back. Restarting the app does the same thing
3) The treatment tab then shows the TT as set - presumably because it has updated from NScout - although this does not then cancel
This issue does not occur in 2.5.1

**Comment by AndreySlepykh** [comment] 2020-03-18 14:30
Same issue. I get TT working by pressing "Restart" button in the "NSClient" menu.
I'm using AAPS 2.6.0

**Comment by PedanticAvenger** [comment] 2020-03-18 18:58
This behavior was present in all RCs for 2.6,
Workaround is not sync, but imposes a challenge for caregivers entering things like carbs, etc.

**Comment by MilosKozak** [comment] 2020-03-20 11:51
i cannot reproduce this issue
please provide NS version
turn on all DATA and NS logging in AAPS and provide logs when this happen

**Comment by AndreySlepykh** [comment] 2020-03-20 14:34
AndroidAPS 2.6.0
Build: c3dbd1ec2-2020.03.16-19:15
Flavor: fullrelease
Nightscout version: 13.0.1
[AndroidAPS_LOG_1584714685960.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4360135/AndroidAPS_LOG_1584714685960.log.zip)
![Screenshot (20 Mar 2020 17_33_22)](https://user-images.githubusercontent.com/62176358/77173732-07cff600-6ad1-11ea-9b00-1b79b3a8cd40.png)

**Comment by MilosKozak** [comment] 2020-03-20 18:22
the cancel comes from NS as malformed record
there is nothing i can do with this.
set to upload only

**Comment by erinlgrant** [comment] 2020-03-21 03:15
Hi Milos, I don't really know enough about the systems and programming and really do appreciate your efforts that you put in for the development of android aps it is just fantastic.. However, I do not get this glitch with 2.5.1. and have gone back to that version as I use NSClient to help manage my two children by either doing a profile switch or setting temporary targets. With the way it is cancelling I actually don't know if it gets set or not on their phones when they are remote. 
Setting to upload only does remove the problem on the my child's phone but it then means that I can not make remote changes from the NSclient app which is a great feature. I too have Nightscout version 13.0.1 only experienced the problem with 2.6.0. I think it was only associated with manual temp targets, so the automatic one after a hypo treatment did not cancel - I would be willing to reload 2.6.0 NSClient and APS again to test the scenarios to check exact combinations and send logs. If you think it is something that could be looked at further, because for some reason it is only happening with 2.6.0. and I use the NSclient to control APS quite a bit for my youngest child. Thanks Chris

**Comment by killakitty69** [comment] 2020-03-21 22:11
@MilosKozak it does seem strange that nothing has changed in Nightscout, but AAPS updated from 2.5.1 to 2.6 and now for some reason all temp targets are being cancelled shortly after being enacted and you think there is nothing you can do.  I'm reluctant to go to upload only because I use Nightscout for my profiles and I use NSClient on another phone as well.

Thanks!

**Comment by analogmonster** [comment] 2020-04-17 17:15
I also was having this issue. I opened my treatment log on the temp target page and had 2 cancels. Removed those cancels, and my temp target starts working again. In other words, I removed the malformed records so now AAPS knows what TT to display. 

So it will only be an issue for me if I have more malformed records. I don’t know where my malformed records came from. AAPS is the only device I have that uploads to NS, so if it reoccurs I will report back here

**Comment by analogmonster** [comment] 2020-04-18 19:44
@MilosKozak Sorry for digging up a closed issue, I am another user experiencing the same issue and want to help come to a resolution.  Is there any data I can provide?  This happens 100% of the time for me with TTs.  I am running 2.6.1 and nightscout 13.0.1.  I also have recently had a clean of my mLab database and nightscout admin tools says there are no future entries.

I set my TT, AAPS calculates new basal rate and updates pump.   Immediately after the pump acknowledges AAPS removes the TT, calculates basal and updates the pump again.  On nightscout the TT is still displayed.

I view the entries in my mLab.  I can see the TT, I cannot see anything in the timeframe that could be cancelling them.  I note the number of entries, before using "refresh events from NS" in the treatment tab of AAPS.  The TT then appears in AAPS again, but there has been no change to the mLab database.  AAPS will cancel the TT again in the near future.  AAPS does not cancel the TT if I use the "Restart" button in the "NSClient" menu.

**Comment by MilosKozak** [comment] 2020-04-19 09:20
1) turn automation oof
2) set NS to upload only

does this resolve the issue?

**Comment by UphwbKpqSm47z3qewH9x** [comment] 2020-04-20 14:57
Setting NS to upload only resolved the issue for me on 2.6.0

**Comment by analogmonster** [comment] 2020-04-21 16:48
Yes, setting to upload only did allow the TT but I wanted to get to the cause.  I might have fixed my problem.  I used to use xdrip, hadn't disabled its Nightscout sync.  Turned that off and now my TT stays.  It is strange because it doesn't seem to be doing anything to the database., and it wasn't doing it until I updated AAPS  You can close this again, sorry for the bother but hopefully someone else with the same problem can double check they haven't got some kind of writing to Nightscout conflict

**Closed** 2020-04-22 15:11 UTC
Labels: more info
