### ISSUE TITLE
2.6.7-dev When using mmol/L units, when the blood glucose is below the visible range, the blood glucose point does not appear on the chart on the watch

### ISSUE THREAD

**Issue by DriverTicks** [MilosKozak/AndroidAPS#2771] opened 2020-06-24 12:08 UTC
When using mmol/L units, when the blood glucose is below the visible range, the blood glucose point does not appear on the chart on the watch.

As I have shown in the two pictures below, it is normal when I use mg/dl units, but when using mmol/L units, the curve below the view range will disappear.
![image](https://user-images.githubusercontent.com/30198264/85553263-5d7ae800-b656-11ea-928d-cea2313bcd93.png)
![image](https://user-images.githubusercontent.com/30198264/85553298-64095f80-b656-11ea-8fd5-e265f0601f78.png)

--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment] 2020-06-24 15:47
i think this is maybe alredy fixed in dev. can you test it?

**Comment by DriverTicks** [comment] 2020-06-24 15:56
Thanks, but I am using the latest development version and this issue has not been resolved in PR #2747

**Comment by Philoul** [comment] 2020-06-24 22:32
After a switch in mmol, I confirm this issue.
I'll try to find a solution

**Comment by Philoul** [comment] 2020-06-25 12:29
I found this issue but I'm a little bit surprised because it's located in wear app that didn't change recently... Do you have this issue with 2.6 released version of AAPS ?

I think explain is a units change in WatchUpdaterService for data sent to watch in 2.6.7 compared to 2.6.1
=> 2.6.1 and earlier : raw data always sent in mg/dl with only "String" BG value converted in current units (mg/dl or mmol)  for watchface
=> 2.6.7 : raw data converted in current units before sent to watch...

@MilosKozak do you prefer I keep 2.6.1 logic and fix WatchUpdaterService for all data sent to watchface or should I change Wear app to fix this issue ?

**Comment by DriverTicks** [comment] 2020-06-25 14:06
This problem did not appear in 2.6.1.4 and earlier versions. In the version after 2.6.1.4, there are various display problems on the watch interface, when the blood glucose unit is mmol/L.

**Comment by Philoul** [comment] 2020-06-25 15:23
@DriverTicks for me it's now ok in mmol with my latest PR 
=> can you verify on your side with all "various display problems" you had?

I modified WatchUpdaterServices to send all raw values in mg/dl as it was done before (include BG values, LowLine and HighLine) because it's hard coded in mg/dl in Wear code for graph
=> On my side when I switch units, everything seems to be Ok in both units (graphs, colors and values in watchface - tested with AAPSV2)

**Comment by DriverTicks** [comment] 2020-06-25 18:33
@Philoul Thanks.I have tested it(tested with AAPSV2). colors and values in watchface are Ok.It can also be displayed normally when the blood glucose is lower than the lower limit. But, when the blood glucose unit is mmol/L, there is a problem with the position of the prediction curve. Just like the photo below me.
![image](https://user-images.githubusercontent.com/30198264/85778193-e9733980-b754-11ea-919a-a4156354304d.png)
![image](https://user-images.githubusercontent.com/30198264/85778467-2d663e80-b755-11ea-8719-fd67e05f96e7.png)

**Comment by Philoul** [comment] 2020-06-25 19:38
@DriverTicks thanks for your answer
- PR updated with prediction lines

Ok on my side after resend all data, can you confirm that now everything is ok in mmol units please ?

**Comment by DriverTicks** [comment] 2020-06-26 04:38
@Philoul 
After testing everything is fine.
Thanks.

**Closed** 2020-06-26 05:56 UTC

**Comment by Philoul** [comment] 2020-07-06 23:26
@DriverTicks does it still work with latest beta2 ?
see https://github.com/MilosKozak/AndroidAPS/issues/2760

**Comment by hartlijn** [comment] 2020-07-10 07:30
@Philoul in beta 2 the BG under lower limit is shown correctly in the graph. Thing left unsolved is the warning colour issue.

**Comment by Philoul** [comment] 2020-07-10 22:09
Unfortunatly I can't reproduce this issue on my side...
Code seems to be correct and it works on my watch (I tried to switch several times in mmol units and each times colors, curves and values are ok...)
