### ISSUE TITLE
[2.0 RC 5.1]: Setting new basal / cancel current temp basal (using extended bolus) fails, extended bolus continues.

### ISSUE THREAD

**Issue by dideldum** [MilosKozak/AndroidAPS#1284] opened 2018-08-01 09:56 UTC
I have 2.0 RC 5.1 running since 2018-07-17 (maybe it was still RC 5 then and changed a bit later to 5.1) with a Dana R.

In these two weeks it happened two times, that a high temporary basal rate (effectively executed with an extended bolus) was not cancelled.

In the Loop tab I could see the status "waiting for pump response".

The "Cancel temporary basal rate" button on the Actions tab didn't work, the high temporary BR was not cancelled.

I disabled then in the Dana preferences in AndroidAPS the usage of the extended bolus. Now a new button on the Actions tab appeared below the "Cancel temp basal" button, the "Cancel extended bolus" button. This button worked, the extended bolus was cancelled on the pump now.

After that I enabled the extended bolus for basal rates again and it continued working well. Until once it failed again.

As I don't remember the time of these events well, I searched the logs (thanks to Adrian), and I think, I found the log of this issue. Have a look at 11:54:10.176 , I think, there the problem starts. You can see an unhandled exception with SQL-statements regarding the extended bolus following there. There are more SQL exceptions 5 minutes later, which I guess, still belong to the problem.

[AndroidAPS._2018-07-23_00-00-01_.1.log](https://github.com/MilosKozak/AndroidAPS/files/2248950/AndroidAPS._2018-07-23_00-00-01_.1.log)

**Comment by dideldum** [comment] 2018-08-01 10:09
Just to add: I probably disabled/enabled bluetooth once or twice, after the problem occured, so there are some bluetooth disconnects/connects. I hoped to make AAPS "initialize" the connection again to cancel the extended bolus, but it also didn't work.

**Comment by dideldum** [comment] 2018-08-01 10:12
Just in case, that this is not the right log, which are the keywords to look in the logfiles to find, when the "Cancel extended bolus" button was pressed? I did it in theses two situations and never more, so this would show clearly the time of the problem.

**Comment by Pallesauka** [comment] 2018-08-01 11:43
I experienced a similar issue where a temp basal was not properly canceled. Look at 04:06:58 in this log file. A high temp basal of 0.23 (0.1 extended basal, 0.13 normal basal) was active. When the clock turned 04.00 our profile basal rate changed from 0.13 --> 0.18. At 04:06:58 there was a new run of AMA oref0 stating that the temp basal should be canceled. However it did not. This occurred in closed loop using master build 050454fc7-2018.07.27 on a samsung galaxy A3 with android 8.0.

I had a similar occurrence in open loop with the same build where AAPS would not update to a new suggested, lower basal while having high temp with extended bolus active. I will look further to try and find exactly at what time this occurred and upload a separate log.

I have provided the logfile from the closed loop event at 04.06.58 along with a few screenshots shortly after the time of the AMA calculation showing some kind of error when trying to cancel the temp basal as well as the current active temp.

![38177074_10155278473676307_7748320116667842560_n](https://user-images.githubusercontent.com/34350745/43519736-e0a2dcda-9590-11e8-86ad-78ba5eaf0126.jpg)
![38130116_10155278473756307_7640126394378223616_n](https://user-images.githubusercontent.com/34350745/43519740-e36e8fa4-9590-11e8-8e16-63d90630a93d.jpg)
![38195926_10155278473826307_551612519660126208_n](https://user-images.githubusercontent.com/34350745/43519744-e5732288-9590-11e8-825e-dfca7ecc319e.jpg)


[AndroidAPS._2018-08-01_04-18-08_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2249251/AndroidAPS._2018-08-01_04-18-08_.0.zip)

**Comment by Pallesauka** [comment] 2018-08-02 06:56
I found yet another instance when APPS did not execute the suggested temp basal of AMA. This does however not include extended boluses but only normal temp basal changes. Eventually I had to execute this temp basal manually through the loop tab.
Our BG was on the way down from ~8mmol. Out target was 6mmol. We dropped through our target AMA oref0 suggested to lower the basal already at 07:09:16 (in the log), the basal was then zeroed at 07:14:22 however none of the suggestions were executed in the pump. I had to manually execute the suggestions through the loop tab at 07:19. I have attached some screenshots (unfortunately in Swedish) and the log file.

Im running master build 050454f-2018.07.27 on a samsung galaxy A3 with android 8.0 and a DanaR pump.

![screenshot_20180802-071819_androidaps](https://user-images.githubusercontent.com/34350745/43567375-d92a3786-9631-11e8-9c98-0927522e847f.jpg)
![screenshot_20180802-071810_androidaps](https://user-images.githubusercontent.com/34350745/43567382-ddcf2788-9631-11e8-8fea-9e1a403c7973.jpg)
![screenshot_20180802-071814_androidaps](https://user-images.githubusercontent.com/34350745/43567387-e1028de6-9631-11e8-9391-7783454d0ce8.jpg)

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2252437/AndroidAPS.log)

**Comment by dideldum** [comment] 2018-08-02 17:18
Today quite often the setting/cancelling of a temp basal using the extended bolus doesn't work.

Here an excerpt of the log, when it happened. It looks for me, as if there were a race condition in the SerialIOThread, which tells "response not received", but immediately after that the response seems to be there!

19:09:05.602 [Thread-5305] DEBUG [QueueThread.run():126]: QUEUE: performing TEMPBASAL 0.5442 U/h 30 min
19:09:05.605 [Thread-5305] DEBUG [DanaRPlugin.setTempBasalAbsolute():329]: setTempBasalAbsolute: Extended bolus in progress: false rate: 0.0U/h duration remaining: 0min
19:09:05.606 [Thread-5305] DEBUG [DanaRPlugin.setTempBasalAbsolute():330]: setTempBasalAbsolute: Rate to set: 0.30000000000000004U/h
19:09:05.607 [Thread-5305] DEBUG [DanaRPlugin.setTempBasalAbsolute():350]: setTempBasalAbsolute: Setting extended: 0.15000000000000002U  halfhours: 1
19:09:05.619 [Thread-5305] DEBUG [MsgSetExtendedBolusStart.<init>():29]: Set extended bolus start: 0.15U halfhours: 1
19:09:05.621 [Thread-5305] DEBUG [SerialIOThread.sendMessage():151]: >>>>> CMD_PUMPSET_EXPANS_INS_S 7e 7e 06 f1  04 07 00 0f  01 0c 28 2e  2e 
19:09:05.984 [Thread-5324] DEBUG [SerialIOThread.run():75]: <<<<< CMD_PUMPINIT_TIME_INFO 7e 7e 0a f3  03 01 12 08  02 13 09 03  b2 32 94 2e  2e 
19:09:05.985 [Thread-5324] DEBUG [MsgInitConnStatusTime.handleMessage():57]: Pump time: Thu Aug 02 19:09:03 GMT+02:00 2018
19:09:05.986 [Thread-5324] DEBUG [MsgInitConnStatusTime.handleMessage():58]: Version code: 178
19:09:06.073 [Thread-5324] DEBUG [SerialIOThread.run():75]: <<<<< CMD_PUMPINIT_BOLUS_INFO 7e 7e 0f f3  03 02 09 05  02 58 00 00  02 58 02 58  02 58 18 83  2e 2e 
19:09:06.075 [Thread-5324] DEBUG [MsgInitConnStatusBolus.handleMessage():38]: Is Extended bolus enabled: true
19:09:06.077 [Thread-5324] DEBUG [MsgInitConnStatusBolus.handleMessage():39]: Bolus increment: 0.05
19:09:06.078 [Thread-5324] DEBUG [MsgInitConnStatusBolus.handleMessage():40]: Bolus max: 6.0
19:09:06.243 [Thread-5324] DEBUG [SerialIOThread.run():75]: <<<<< CMD_PUMPINIT_INIT_INFO 7e 7e 19 f3  03 03 00 00  ee 13 00 13  88 4f 1e 02  00 00 16 00  00 00 00 00  00 00 64 00  29 34 2e 2e  
19:09:06.244 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():42]: Delivery prime: false
19:09:06.245 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():43]: Delivery step bolus: false
19:09:06.246 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():44]: Delivery basal: false
19:09:06.247 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():45]: Delivery ext bolus: false
19:09:06.249 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():50]: Pump suspended: false
19:09:06.250 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():51]: Calculator enabled: false
19:09:06.251 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():52]: Daily total units: 6.802666666666667
19:09:06.252 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():53]: Max daily total units: 50
19:09:06.253 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():54]: Reservoir remaining units: 185.108
19:09:06.254 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():55]: Bolus blocked: false
19:09:06.255 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():56]: Current basal: 0.22
19:09:06.256 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():57]: Current temp basal percent: 0
19:09:06.258 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():58]: Is extended bolus running: false
19:09:06.261 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():59]: statusBasalUDOption: 0
19:09:06.261 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():60]: Is dual bolus running: false
19:09:06.262 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():61]: Extended bolus rate: 0.0
19:09:06.264 [Thread-5324] DEBUG [MsgInitConnStatusBasic.handleMessage():62]: Battery remaining: 100
19:09:06.270 [Thread-5324] DEBUG [SerialIOThread.run():75]: <<<<< CMD_PUMPINIT_OPTION 7e 7e 0e f3  03 04 00 01  01 00 0a 0a  04 0a 00 30  b1 ca c3 2e  2e 
19:09:06.271 [Thread-5324] DEBUG [MsgInitConnStatusOption.handleMessage():33]: Pump password: 1234
19:09:10.824 [Thread-5305] WARN  [SerialIOThread.sendMessage():169]: Reply not received CMD_PUMPSET_EXPANS_INS_S
19:09:10.826 [Thread-5305] DEBUG [SerialIOThread.sendMessage():151]: >>>>> CMD_PUMP_EXPANS_INS_I 7e 7e 03 f1  02 07 c2 e7  2e 2e 
19:09:11.102 [Thread-5324] DEBUG [SerialIOThread.run():75]: <<<<< CMD_PUMP_EXPANS_INS_I 7e 7e 0c f2  02 07 00 00  00 00 00 00  00 00 00 94  b2 2e 2e 
19:09:11.103 [Thread-5324] DEBUG [MsgStatusBolusExtended.handleMessage():52]: Is extended bolus running: false
19:09:11.104 [Thread-5324] DEBUG [MsgStatusBolusExtended.handleMessage():53]: Extended bolus min: 0
19:09:11.105 [Thread-5324] DEBUG [MsgStatusBolusExtended.handleMessage():54]: Extended bolus amount: 0.0
19:09:11.106 [Thread-5324] DEBUG [MsgStatusBolusExtended.handleMessage():55]: Extended bolus so far in minutes: 0
19:09:11.108 [Thread-5324] DEBUG [MsgStatusBolusExtended.handleMessage():56]: Extended bolus absolute rate: 0.0
19:09:11.109 [Thread-5324] DEBUG [MsgStatusBolusExtended.handleMessage():57]: Extended bolus start: Thu Jan 01 01:00:00 GMT+01:00 1970
19:09:11.110 [Thread-5324] DEBUG [MsgStatusBolusExtended.handleMessage():58]: Extended bolus remaining minutes: 0
19:09:11.313 [Thread-5305] ERROR [AbstractDanaRPlugin.setExtendedBolus():250]: setExtendedBolus: Failed to extended bolus
19:09:11.315 [Thread-5305] ERROR [DanaRPlugin.setTempBasalAbsolute():353]: setTempBasalAbsolute: Failed to set extended bolus
19:09:11.316 [Thread-5305] DEBUG [CommandTempBasalAbsolute.execute():38]: setTempBasalAbsolute rate: 0.5442 durationInMinutes: 30 success: false enacted: false
19:09:11.418 [Thread-5305] DEBUG [QueueThread.run():148]: QUEUE: waiting for disconnect
19:09:12.420 [Thread-5305] DEBUG [QueueThread.run():148]: QUEUE: waiting for disconnect
19:09:13.422 [Thread-5305] DEBUG [QueueThread.run():148]: QUEUE: waiting for disconnect
19:09:14.424 [Thread-5305] DEBUG [QueueThread.run():148]: QUEUE: waiting for disconnect
19:09:15.427 [Thread-5305] DEBUG [QueueThread.run():148]: QUEUE: waiting for disconnect
19:09:16.429 [Thread-5305] DEBUG [QueueThread.run():141]: QUEUE: queue empty. disconnect
19:09:16.433 [Thread-5324] DEBUG [SerialIOThread.disconnect():200]: Disconnected: EndOfLoop
19:09:16.434 [Thread-5305] DEBUG [SerialIOThread.disconnect():200]: Disconnected: Queue empty
19:09:16.435 [Thread-5305] DEBUG [QueueThread.run():145]: QUEUE: disconnected

**Comment by MilosKozak** [comment] 2018-08-03 09:27
@Pallesauka it's the same issue. pump didn't respond to command for more than 5 sec

**Comment by Pallesauka** [comment] 2018-08-03 10:30
@MilosKozak I bought the phone 2 weeks ago and it was factory reset at that time. It is a Samsung Galaxy A3 which I know for a fact that many others are using without hiccups. Do you have any idea what I could do to make this work better? because I cannot make anything usefull of your previous comment.

**Comment by dideldum** [comment] 2018-08-03 10:32
But the pump responds fine in most of the cases.
So what is the reason, that sometimes the communication doesn't work?

**Comment by dideldum** [comment] 2018-08-03 10:37
And furthermore:
When I read the pump informations after that issue, there is no problem at all between the phone and the pump to communicate! It is ONLY the setting/cancelling of the extended bolus.

**Comment by dideldum** [comment] 2018-08-03 10:37
Could we please reopen this issue?

**Comment by dideldum** [comment] 2018-08-03 10:41
@MilosKozak And please see my first post: Disabling extended bolus in AAPS Dana settings and press then the cancel extended bolus button in actions worked! So there is no basic problem in the communication with the pump!

**Comment by Pallesauka** [comment] 2018-08-03 11:04
@MilosKozak Since this occured on two different phone models, two different android versions, two different AAPS builds and two different DanaR pumps I think it deserves some more attention, especially since its a huge safety issue. We went low the other night as a result of this communication error.

**Comment by dideldum** [comment] 2018-08-03 11:39
Just to add the configuration, which has the described problem:
Blackview BV6000 (Android 6.0)
Dana R (Model: 03 Protokoll: 03 Code: B2)
AAPS 2.0RC5.1

**Comment by Pallesauka** [comment] 2018-08-03 11:44
And we're on:
Samsung galaxy A3 (SM-A320FL) with Android 8.0
AAPS master build 050454f-2018.07.27
DanaR: OLD (unknown)

**Comment by MilosKozak** [comment] 2018-08-03 11:59
19:09:10.824 [Thread-5305] WARN [SerialIOThread.sendMessage():169]: Reply not received CMD_PUMPSET_EXPANS_INS_S

this is the starting issue
it can be related BT stack, overloaded phone etc

**Comment by Pallesauka** [comment] 2018-08-03 12:02
@MilosKozak How would we go about finding the root cause for this? Is there a maximum time AAPS waits for confirmation?

**Comment by dideldum** [comment] 2018-08-03 12:05
@MilosKozak But immediately after the message "Reply not received" you see the SerialIOThread SENDING the command AND RECEIVING the a response. How does this conform to the error?

**Comment by MilosKozak** [comment] 2018-08-03 12:07
pump usually responds in hundrets of milliseconds. timeout for broken comm is 5 sec

**Comment by MilosKozak** [comment] 2018-08-03 12:08
look for `message.wait(5000);` in `SerialIOThread.java` . you may change it but i don't believe it's a good idea

**Comment by dideldum** [comment] 2018-08-03 12:09
Regarding the log the SEND was done after the "Reply not received" WARN at 19:09:10.826 and the reply was received 300ms later. What is wrong with that?
Why is the error BEFORE sending and getting a correct response in the required time?

**Comment by MilosKozak** [comment] 2018-08-03 12:13
it can be only loging synchronization issue or like i said overloaded phone - no CPU available for `mOutputStream`

**Comment by Pallesauka** [comment] 2018-08-03 12:16
hm. ok. What should I do then? Flash to the latest firmware in the phone?

**Comment by MilosKozak** [comment] 2018-08-03 12:17
or try dev branch, it's 6 months newer with many improvements. but this serial communication is the same

**Comment by Pallesauka** [comment] 2018-08-03 12:24
If the communication is the same I doubt it will lead to any improvements related to this issue, wouldnt you agree?

**Comment by dideldum** [comment] 2018-08-03 12:25
@MilosKozak I cannot imagine, that it is a CPU overload. The BV6000 is quite fast compared with my P8000.
And I monitored it once when this error was. With each AMA calculation it was tried again to cancel the extended bolus, but failed.
But when I did a manual communication with the pump (with the bluetooth icon in the Dana tab, or after canceling the extended bolus usage in the settings with the "cancel extended bolus" button) all the communications worked flawlessly!
I tried it like this: cancel extended bolus failed by AAPS after AMA calculation (Loop module shows still "waiting for pump response"). I tapped on Bluetooth status icon on the Dana tab - communication was working fine. I did a "show profile" and a "reload profile" in the Dana tab. It was working fine. Then the next AMA calculation came and again wanted to cancel the extended bolus. And again it failed. Only when I disabled the extended bolus usage and canceled manually, it worked.
All this cannot be, if the CPU is overloaded.

**Comment by MilosKozak** [comment] 2018-08-03 12:28
the problem is not AAPS but phone or android. only running different apllications in phone may change something

**Comment by MilosKozak** [comment] 2018-08-03 12:31
@dideldum ok, what's you explanation? the code for sending messages is always the same

**Comment by dideldum** [comment] 2018-08-03 12:37
@MilosKozak I don't have an explanation, unfortunately. The code in SerialIOThread.SendMessage seems to be fine. But still I would like to know, why the warn message came before the send log entry. This would mean, the logger has not written the send log entry for 5000ms, while SendMessage was waiting for the timeout. But then immediately the send log entry AND a receive log entry is written.
For me it looks more like a synchronisation problem on message?

**Comment by Pallesauka** [comment] 2018-08-03 13:01
I also have tons of these:
ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus
and
20:50:52.248 [Thread-451] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:262]: setTempBasalPercent: Failed to set temp basal
and
22:17:47.633 [Thread-1170] DEBUG [info.nightscout.androidaps.plugins.PumpDanaR.comm.MsgSetExtendedBolusStart:39]: Set extended bolus start result: 0 FAILED!!!

But perhaps thats the end result of this error chain

**Comment by dideldum** [comment] 2018-08-03 13:08
My java development times have been some years in the past, but I noticed in SerialIOThread:

The SendMessage function operates with the member variable processedMessage and is synchronized. But the run() also operates with processedMessage and doesn't do a synchronized(this). Could this lead to a problem? So the sender thread (executing SendMessage()) and the receiver thread (being in the run() loop) don't have a really synchronized access on processedMessage, do they?

**Comment by MilosKozak** [comment] 2018-08-03 13:23
try different phone. i'm not able help more

**Comment by dideldum** [comment] 2018-08-05 08:03
@MilosKozak  PLEASE reopen this issue again!!!

I had this problem just now again. Then I simply disabled the usage of extended bolus and pressed again on the "Execute" buttons in the AMA tab and the Loop tab. And the setting of the temporary basal immediately worked, while before with the extended bolus we had the same problem.

Furthermore it is definitely a bug, that using the extended bolus the Loop tab stays in the state "waiting for pump response", though obviously there was already the timeout/error situation.

PLEASE REOPEN IT AGAIN. IT DEFINITELY CANNOT BE CLOSED AS A PHONE PROBLEM!

**Comment by Pallesauka** [comment] 2018-08-05 21:25
Both me and @dideldum are using Libre + MiaoMiao/bluecon + xdrip+ as BG source and we are currently looking into if xdrips way of staying connected to the BG sources are somehow interfearing with AAPS in communicating through BT. 
We are now running Xdrip +libre+miaomiao/bluecon on a separate device to make sure that AAPS can communicate freely on the phone with AAPS. Will report back soon with results and logs.

**Comment by Pallesauka** [comment] 2018-08-06 12:34
Ok, So I have been running AAPS now for 12h on a new phone (Oneplus5 with android 8.1.0). While trying a new phone for AAPS i kept xdrip+miaomiao+libre connected to the old phone (Samsung galaxy A3) to make sure the bluetooth communication was free as much as possible for AAPS.
Unfortunately I got more than 10 communication errors over the 12h period.

00:13:08.109 [Thread-1095] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus
02:08:00.337 [Thread-1909] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus
02:53:02.767 [Thread-2226] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus
03:03:00.624 [Thread-2287] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus
04:07:56.905 [Thread-2730] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus
04:27:57.380 [Thread-2870] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus
04:48:13.483 [Thread-3022] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:327]: cancelExtendedBolus: Failed to cancel extended bolus
04:57:59.344 [Thread-3103] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus
05:38:40.738 [Thread-3396] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus

etc.... So it does not seem to be a phone problem. Neither is is a xdrip over load BT problem. What can be checked in the AAPS code?

**Comment by Pallesauka** [comment] 2018-08-06 21:23
I just updated to RC 6.1 and still the temp basals / extended temp basals keep failing to either deliver or cancel. Im soon out of ideas. Can anyone help? 
Have tried two different phones, both master branch and RC6.1, with and without Xdrip (master) on the AAPS phone.

**Comment by dideldum** [comment] 2018-08-12 13:58
For a few days I have RC6.1 running and have in Logging I have enabled only PUMP, PUMPBTCOMM, PUMPCOMM  and PUMPQUEUE.

You can see, that many times the "cancel temp bolus" is working fine. Then suddenly it failed.

This is in the middle of the night (03:13). The phone was all the time in a distance of ~1m to the pump. Not moved at all. At 03:18 again the error. At 03:23 it works again. There was no change at all in the environment in this time (indeed we were all sleeping!).

This is now logged with the new Dana RS of my daughter, the logs before were taken using my Dana R (but also running with the same phone of my daughter before). So the phone for all logs was the same (Blackview BV6000). The transmitter was changed together with the pump. The Dana R logs were taken, when the Blucon was used. The Dana RS logs were taken with the MiaoMiao, which arrived by accident the same day, when we received the Dana RS.
[AndroidAPS.log.zip](https://github.com/MilosKozak/AndroidAPS/files/2281013/AndroidAPS.log.zip)

**Comment by Pallesauka** [comment] 2018-08-15 18:43
I caught the loop in the moment when it failed to adjust temp basal. It seems like it gets caught up in a loop waiting for confirmation of something. Just like previous posts suggests.

![screenshot_20180815-173859_androidaps](https://user-images.githubusercontent.com/34350745/44166421-a7462f00-a0cb-11e8-8e24-6c325177f99b.jpg)
![screenshot_20180815-173906_androidaps](https://user-images.githubusercontent.com/34350745/44166422-a7462f00-a0cb-11e8-83e8-a0e41c00a4e3.jpg)

**Comment by Pallesauka** [comment] 2018-08-21 08:27
I talked to quite alot of ppl using the DanaR with AAPS and here are a set of logs from a different user. They show the same behaviour where temp basals / extended boluses either fail to set or cancel.

It is also a complete different set of hardware: DanaR, HTC One m8, Android 6.0.1; aaps RC 6.1, libre with rfduino.

[AndroidAPS._2018-08-20_17-46-11_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2305430/AndroidAPS._2018-08-20_17-46-11_.0.zip)
[AndroidAPS._2018-08-20_00-02-44_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2305431/AndroidAPS._2018-08-20_00-02-44_.0.zip)

**Comment by MilosKozak** [comment] 2018-08-21 08:49
you need to turn on BT debugging in maintenance too

**Comment by Pallesauka** [comment] 2018-08-21 09:02
@MilosKozak ok, here are a few of my logs with BT debugging enabled.
[AndroidAPS._2018-08-20_00-00-05_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/2305566/AndroidAPS._2018-08-20_00-00-05_.2.zip)
[AndroidAPS._2018-08-20_00-00-05_.3.zip](https://github.com/MilosKozak/AndroidAPS/files/2305568/AndroidAPS._2018-08-20_00-00-05_.3.zip)

**Comment by MilosKozak** [comment] 2018-08-21 15:26
fixed in https://github.com/MilosKozak/AndroidAPS/commit/32d9a8b4d63f83947cda05d2fe8b031d6da89940

**Closed by MilosKozak** 2018-08-21 15:26 UTC
Labels: help wanted

**Comment by dideldum** [comment] 2018-08-21 15:33
@MilosKozak Is there a reason, that the handshake is only implemented for Dana R and not for Dana RS? I had this issue also with the RS, see: https://github.com/MilosKozak/AndroidAPS/issues/1284#issuecomment-412344710
