### ISSUE TITLE
[2.6 RC5] Simultaneous recording of "pump site change" and "cartridge change" not possible

### ISSUE THREAD

**Issue by goomStar** [MilosKozak/AndroidAPS#2374] opened 2020-01-16 16:36 UTC
When using the Prime/Fill dialogue in actions tab with the intention to record pump site change and cartridge change at once (ticking both checkboxes), only the cartridge entry will be written.
Using singular choices works fine.

(is it my flawed phone again? xD)

Would be nice, if someone else could give it a try. I used the prime/fill button with 0.00U insulin.

Logfiles. Performed described procedure straight before exporting the file
[AndroidAPS_LOG_1579192475598.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4072426/AndroidAPS_LOG_1579192475598.log.zip)

**Comment by jotomo** [comment] 2020-01-16 16:53
Duplicate of #2369 
Will be fixed via #2373

**Closed** 2020-01-16 17:10 UTC
