### ISSUE TITLE
[Medtronic] Double entry of insulin after using calculator

### ISSUE THREAD

**Issue by lydiaengler** [MilosKozak/AndroidAPS#2086] opened 2019-09-30 22:20 UTC
[AndroidAPS_LOG_1569877092228.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3673638/AndroidAPS_LOG_1569877092228.log.zip)

Calculator used - double insulin entry as can be seen from screenshot.

Using 2.4 RC2 / 722 pump +RL

Scenario was, entered 10g using carbs button.  Few minutes later, entered another 10 g with carbs button.  waited a few seconds to check COB had increased to 20, then pressed calc button and accepted the recommended 3.9 U which was delivered successfully.

![IMG_0885](https://user-images.githubusercontent.com/45319130/65921005-ca6b9500-e3d8-11e9-85e9-81f64b1b4bc7.JPG)

**Comment by andyrozman** [comment] 2019-09-30 22:49
I will try to reproduce this, but why didn't use Bolus Calculator directly, adding 20 g there and executing...

**Comment by lydiaengler** [comment] 2019-09-30 22:57
Well, was a bit low when eating the first 10g, so decided not to take any insulin bolus but just “tell” AAPS about the carb intake. But when we took more, decided to bolus.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andyrozman** [comment] 2019-10-09 10:27
Just one side note.... Whatever you took for low BG, it needs at least 10-20 minutes to work... Even sugar wouldn't give you any result in 5 minutes...

**Comment by lydiaengler** [comment] 2019-10-09 10:32
Thanks, although she didn’t take more because she hadn’t seen a BG rise, was just because she felt like eating more!

Btw we yesterday saw the double insulin entry in another scenario:  entered 40g ecarbs over 2 hours. A minute later, gave a 4.5u bolus. That bolus appeared twice in treatments and was incremented twice as IOB



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andyrozman** [comment] 2019-10-09 10:42
I made some changes, that will add more debug info (#2100), they probably won't fix this, but I will get more info (about what we have in database)... 
If you can please try code in that branch and let me know if duplicates still happen... And when they happen, please attach info. 
No all double entries are the same. So please open another ticket for that 2nd problem (if you have all data - log, picture)... if not see if you can reproduce it with this new code, so that I can see what is happening in database.

**Comment by lydiaengler** [comment] 2019-10-30 12:54
Screenshot and logs attached.  Double entry of 5.2 U following use of calc at 10.59.  Bolus debugging is switched on.
[AndroidAPS_LOG_1572439576273.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3788956/AndroidAPS_LOG_1572439576273.log.zip)
![Screenshot_20191030-124543](https://user-images.githubusercontent.com/45319130/67859796-5d046e80-fb14-11e9-8a2e-b153138455d9.png)

**Comment by lydiaengler** [comment] 2019-10-31 20:58
@m4nnihuber are double entries still absent?  Have you sent logs?  @andyrozman does this fact help you to nail the issue?

**Comment by m4nnihuber** [comment] 2019-11-01 09:27
@lydiaengler actually no double entries since i switched from SMB to AMA and back.

maybe you give it a try so we know if this is a possible workaround?

**Comment by lydiaengler** [comment] 2019-11-01 09:52
Thanks for that.  Actually, we have just re-installed AAPS from scratch, including starting from a blank preferences file (due to some issues we had had with objectives).  We haven't yet seen the double entries.  If and when we see them, we will try your suggestion.

**Comment by andyrozman** [comment] 2019-12-22 19:17
Fixed in release 2.6-rc1, closing.

**Closed by andyrozman** 2019-12-22 19:17 UTC
