### ISSUE TITLE
2.6.6-dev after sensor change first reading aaps crashed

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2714] opened 2020-06-11 20:35 UTC
Build 5395ca4e7 

After sensor (g6) change, when 1st reading appeared, aaps crashed (phone reboot needed). Not sure why, attaching logs, maybe something is catched. Happened at approx 22:25 (bg 19, in reality 12.2, calibrated 3 times in a row to make it down via dexcom mod app, however its not the root cause, aaps crashed when first value after change popped up )

[AndroidAPS_LOG_1591907330920.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4767187/AndroidAPS_LOG_1591907330920.log.zip)

**Comment by MilosKozak** [comment] 2020-06-15 11:14
no related info in logs. I never had this issue and i'm not able to reproduce it.
Closing for now. Create new issue if you have more info

**Closed by MilosKozak** 2020-06-15 11:14 UTC
