### ISSUE TITLE
[RC5.1] Treatment tab sometimes shows duplicates

### ISSUE THREAD

**Issue by 2flea** [MilosKozak/AndroidAPS#1256] opened 2018-07-24 16:33 UTC
I see treatments with source PH + NS (which I consider correct) but sometimes I see two records with the same time and data for a treatment, one with source NS and the other with PH. 

Background info: In NS client setting I only have "locale broadcast" activated. XDrip is not allowed to upload treatments.

![image](https://user-images.githubusercontent.com/38214111/43182167-9c664a08-8fe0-11e8-8483-bb6b3dd899c4.png)

[double_treatment_PH_NS.log](https://github.com/MilosKozak/AndroidAPS/files/2226682/double_treatment_PH_NS.log)

**Comment by harispoljo** [comment] 2018-07-26 18:57
What pump are you using? If it's the insight pump there is a pull request for that problem #1126

**Comment by 2flea** [comment] 2018-07-26 18:59
Dana RS

**Comment by chriddetyp1** [comment] 2018-08-16 10:14
I noticed the same behaviour with a combo on RC6.1 and as far as I remember also on 5.1. I try to find a proove or screenshot /log.

**Comment by MarieT1D** [comment] 2018-08-17 11:29
I had the same Problem with RC 6.1, Dana RS
![image](https://user-images.githubusercontent.com/37214302/44263249-79bdca80-a21e-11e8-86eb-7f5ea977085e.png)

logs concerning bolus delivered at 00:34 (using Bolus calculator at 00:33)
[AndroidAPS._2018-08-17_01-24-46_.0.txt](https://github.com/MilosKozak/AndroidAPS/files/2297009/AndroidAPS._2018-08-17_01-24-46_.0)

**Comment by MarieT1D** [comment] 2018-08-17 11:30
Again, it is showing "PH" and "NS" in the Image in two tabs instead of one. IOB Shows "9.0I.E." in overview

**Comment by MilosKozak** [comment] 2018-08-17 11:30
Honestly I have no idea how this can happen. I know probably where but not how so I added more logging. 
Update to latest dev and provide new logs pls when this happen again

**Comment by MilosKozak** [comment] 2018-08-17 11:58
OK found, @MarieT1D 's log was more interresting
the problem is that java.util.Date is not thread safe

fixed in dev now

**Closed by MilosKozak** 2018-08-17 11:58 UTC
