### ISSUE TITLE
[Medtronic] Possible missing treatment in Medtronic implementation

### ISSUE THREAD

**Issue by lydiaengler** [MilosKozak/AndroidAPS#2009] opened 2019-08-31 20:15 UTC
OK here's what looks like a serious bug: 25g eaten, calc recommended 5U at 17.15 which was delivered, appears in NS and shows up in pump history on the pump itself. However, looking at the treatment tab a bit later, this 5U delivery didn't appear - only a SMB of 0.5U (which was delivered one minute before). However, if you press refresh treatments from NS, it does then come into the list.

Using 2.4alpha4

Have attached log file.  The initial 5U bolus was at 17.15 and the refresh from NS was at approx 20.30

[AndroidAPS._2019-08-31_14-04-54_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3562793/AndroidAPS._2019-08-31_14-04-54_.0.zip)
[AndroidAPS._2019-08-31_14-04-54_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/3562794/AndroidAPS._2019-08-31_14-04-54_.1.zip)
[AndroidAPS._2019-08-31_14-04-54_.2 1.zip](https://github.com/MilosKozak/AndroidAPS/files/3562795/AndroidAPS._2019-08-31_14-04-54_.2.1.zip)
[AndroidAPS._2019-08-31_14-04-54_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/3562796/AndroidAPS._2019-08-31_14-04-54_.2.zip)
[AndroidAPS._2019-08-31_00-00-00_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3562797/AndroidAPS._2019-08-31_00-00-00_.0.zip)
[AndroidAPS._2019-08-31_00-00-00_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/3562798/AndroidAPS._2019-08-31_00-00-00_.1.zip)
[AndroidAPS._2019-08-31_00-00-00_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/3562799/AndroidAPS._2019-08-31_00-00-00_.2.zip)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by andyrozman** [comment] 2019-08-31 22:41
I am not sure this is bug. If bolus was delivered it was added to AAPS database (and sent to NS). If it wasn't added to AAPS it wouldn't come to NS.
I am not sure Refresh treatments actually works correctly...

**Comment by andyrozman** [comment] 2019-09-08 17:16
If you can reproduce this, I need exact steps and pictures, together with logs. I can't fix problem if I can't reproduce it. If this would happen in "normal" scenarios I am sure someone would say something...

**Comment by andyrozman** [comment] 2019-10-09 10:28
This might have been fixed with #2100. Can you try that version and see if it still happens?

**Comment by lydiaengler** [comment] 2019-10-09 10:36
Can’t till tomorrow but will do then.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andyrozman** [comment] 2019-12-22 19:18
Fixed in release 2.6-rc1, closing.

**Closed by andyrozman** 2019-12-22 19:18 UTC
