### ISSUE TITLE
2.6.5_dev selecting Local Profile for display as a tab undoes automatically

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2591] opened 2020-04-25 13:28 UTC
- The issue happened at 15:21 CEST 25/04/2020
- The Build is 8f8fe39bf-2020.04.24-16:44
- The logs are attached
- A video can be shared if you need
- When I go into Config Builder and select Local Profile in the column of checkboxes on the left, a checkbox on the right becomes available.  If I check that then drop back out of Config Builder, when I re-enter Config Builder, the Local Profile is checked on the left but not on the right.  Local Profile never appears as a tab.  It is still available as an option from the menu on the left.
[AndroidAPS (1).log](https://github.com/MilosKozak/AndroidAPS/files/4533015/AndroidAPS.1.log)

**Comment by jroth-haj** [comment] 2020-04-25 18:50
I can see this Config Builder Issue only in the Profile section on both selections (NS profile and Local Profile). Tested some other sections without this issue.

**Comment by MilosKozak** [comment] 2020-04-28 08:44
you have really strange issues i cannot reproduce. in your case i'd recommend strart a new config

**Comment by guydavies** [comment] 2020-04-28 14:11
I would be unhappy with that response if it means that I have to go back to the start of the objectives.  I haven't reached Objective 10 (I'm still on open loop with virtual pump so I don't expect to get beyond Objective 5 automatically but I also don't expect to be dumped back at Objective 1).

**Comment by jroth-haj** [comment] 2020-05-04 07:54
@MilosKozak The problem persists even after a new installation without importing the settings.
Build: 1cee7e580 (2020-05-04_09:29)

**Comment by Alamo04** [comment] 2020-05-11 18:55
Don't use that tab, but have check it, with the latest dev updates today.

Confirmed - the bug is still alive

**Comment by Philoul** [comment] 2020-05-17 19:59
Maybe I can help, I also have this issue on my phone...
And in log when I play with profil check box on the left, it stil remains "Visible:false" in log

2020-05-17 20:40:18.584 ? D/CONFIGBUILDER: [main]: [ConfigBuilderPlugin.savePref():75]: Storing: ConfigBuilder_PROFILE_LocalProfilePlugin_Enabled:true
2020-05-17 20:40:18.585 ? D/CONFIGBUILDER: [main]: [ConfigBuilderPlugin.savePref():79]: Storing: ConfigBuilder_PROFILE_LocalProfilePlugin_Visible:false
2020-05-17 20:40:24.380 ? D/CONFIGBUILDER: [main]: [ConfigBuilderPlugin.savePref():75]: Storing: ConfigBuilder_PROFILE_LocalProfilePlugin_Enabled:true
2020-05-17 20:40:24.380 ? D/CONFIGBUILDER: [main]: [ConfigBuilderPlugin.savePref():79]: Storing: ConfigBuilder_PROFILE_LocalProfilePlugin_Visible:false

When I select one Profil plugin in config builder (NS or Local), visibility checkbox in unchecked by default (for all other plugin it is checked by default)...

But I don't know how to track the problem to find the root cause into code...

**Comment by CaroGo** [comment] 2020-05-19 12:08
tested with todays update and it is still there...

**Comment by MilosKozak** [comment] 2020-05-23 20:49
fixed by https://github.com/MilosKozak/AndroidAPS/commit/87eb8021de430adf18b313dd095c6f0a2ea6137a

**Closed by MilosKozak** 2020-05-23 20:49 UTC
Labels: 2.6.5, bug
