### ISSUE TITLE
[Important issue] NSClient issue breaks IOB limits (after upgrading from MongoDB to Atlas DB with Heroku?) 

### ISSUE THREAD

**Issue by jarlesb** [MilosKozak/AndroidAPS#2939] opened 2020-08-30 12:19 UTC
[Important issue]
NSClient issue after upgrading from MongoDB to Atlas DB with Heroku.

AAPS jumps back and forth between wrong data from NS and correct data from AAPS. When seeing the NS data, it sets temp basals and SMBs, and increases IOB way beyond limit set by AAPS preferences.

Woke up in the middle of the night with 3 mmol/L and high IOB... And happened again during the day before I applied the fix below.

Cause: seems to be an issue with Nightscout / AtlasDB integration.

See issue description and more experiences here:
https://www.facebook.com/groups/AndroidAPSUsers/permalink/2791018681119531/

Temporary fix: enable "NS upload only (disable sync)"

Build: 2.6.1.1 - 0c8e5b714-2020.04.07-00.13 / fulllrelease / NS 13.0.1

**Comment by MilosKozak** [comment] 2020-08-30 13:51
is data in AAPS correct all the time?

**Comment by jarlesb** [comment] 2020-08-30 19:16
No, AAPS data jumps back and forth as shown in the two FB photos with only 6 minutes apart and one with IOB = -0,92U and one with IOB = 6,15U.

**Comment by Rhabarbara745** [comment] 2020-08-30 19:20
I also noticed this bug few weeks ago.

**Occasionally IOB will be set to 0 for a few seconds -> which results in wrong predictions -> which falsely leads to SMBs being delivered.**

Only workaround as @jarlesb has said is enabling "NS upload only (disable sync)".

See screenshots below:

**Comment by Rhabarbara745** [comment] 2020-08-30 19:26
![Screenshot_20200805-092745](https://user-images.githubusercontent.com/57756367/91667757-2964ed00-eb07-11ea-85cd-ae79adf7eaab.png)
![Screenshot_20200805-092818](https://user-images.githubusercontent.com/57756367/91667763-2ec23780-eb07-11ea-91f9-4a8925897732.png)
![Screenshot_20200805-092754](https://user-images.githubusercontent.com/57756367/91667781-50232380-eb07-11ea-97c4-aad62fb799d9.png)

**Comment by MilosKozak** [comment] 2020-08-31 05:38
the problem is NS sending wrong data. it cannot be resolved in AAPS. Only set upload only which ignores incomming messed up data

**Closed by MilosKozak** 2020-08-31 05:38 UTC

**Comment by scarral** [comment] 2020-08-31 11:23
Milos is NSClient sending wrong data from AAPS to Nightscout or is Nightscout sending wrong data to AAPS? This behaviour also occur in issue #2922 https://github.com/MilosKozak/AndroidAPS/issues/2922.

**Comment by jarlesb** [comment] 2020-08-31 13:46
I have three different IOBs in Xdrip+ (2,33U), AAPS (4,69U — 3,28/1,42) and at the nightscout site (4,5U) Seems strange that they should deviate that much...

**Comment by Rhabarbara745** [comment] 2020-08-31 13:50
thank you for your reply @MilosKozak 
I have no background in java/app-development but wouldn’t it be possible to add some sanity- or plausibility-checks when receiving data from NS?

I don’t see any sense allowing NS to delete Insulin Entries, which have already been delivered by the pump?

In my eyes this behavior is dangerous and shouldn't be ignored, I encountered situations where SMBs got delivered twice (see screenshot below)

**Comment by Rhabarbara745** [comment] 2020-08-31 13:50
![Screenshot_20200804-125956](https://user-images.githubusercontent.com/57756367/91727216-a349b480-eba1-11ea-8ac0-5f52c904a0cf.png)

**Comment by Rhabarbara745** [comment] 2020-08-31 13:57
> I have three different IOBs in Xdrip+ (2,33U), AAPS (4,69U — 3,28/1,42) and at the nightscout site (4,5U) Seems strange that they should deviate that much...

IOB shown in nightscout and AAPS may not be the same because NS uses other calculation for that value – as far as I know this is fine because AAPS always calculates IOB itself based on the Insulin entries

**Comment by MilosKozak** [comment] 2020-09-01 07:55
> thank you for your reply @MilosKozak
> I have no background in java/app-development but wouldn’t it be possible to add some sanity- or plausibility-checks when receiving data from NS?
> 
> I don’t see any sense allowing NS to delete Insulin Entries, which have already been delivered by the pump?
> 
> In my eyes this behavior is dangerous and shouldn't be ignored, I encountered situations where SMBs got delivered twice (see screenshot below)

It depends. Sometimes it maybe be usefull. But ns_upload_only is default on for some time and i recommend keep it unless you really need to have it false

**Comment by Rhabarbara745** [comment] 2020-09-01 09:41
Ah ok thank you, I didn't know ns_upload_only is default on

**Comment by scarral** [comment] 2020-09-01 10:01
@MilosKozak the problem with NS upload only is when you want to follow a child with NSClient and issue commands remotely, namely that not all commands can be done via SMS. Please look at this issue for some commands I have found that were possible through NSClient (if NS upload only in my son's phone were allowed to be turned off) that are not possible via SMS: 
https://github.com/MilosKozak/AndroidAPS/issues/2932

If NS Upload only has to be turned on, it would be nice to have all functionality via SMS commands.
