### ISSUE TITLE
AAPS v1.59dev cannot be started in Android 6.0.1

### ISSUE THREAD

**Issue by Rol71** [MilosKozak/AndroidAPS#717] opened 2018-02-23 12:58 UTC
AAPS v1.59dev with DanaR cannot be started in Android 6.0.1 (Samsung A3 2015). Error message: "Unfortunately AndroidAPS has stopped". After downgrade to v1.58 it works again. 

Date and Time Installation v1.59dev: 2018-02-23-13-47

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1751894/AndroidAPS.log)

**Comment by stavlor** [comment] 2018-02-23 15:37
02-23 10:34:29.738 20733-20733/info.nightscout.androidaps E/INSIGHTPUMP: Main feature detected, preconnecting to pump
02-23 10:34:29.738 20733-20733/info.nightscout.androidaps E/INSIGHTPUMP: Attempting to connect to pump.
02-23 10:34:29.740 20733-20733/info.nightscout.androidaps E/INSIGHTPUMP: Staying connected till: 2018-02-23 10:34:59
02-23 10:34:29.740 20733-20733/info.nightscout.androidaps E/INSIGHTPUMP: Connector::init()
02-23 10:34:29.740 20733-20733/info.nightscout.androidaps E/INSIGHTPUMP: Not trying init due to missing companion app
02-23 10:34:29.741 20733-20733/info.nightscout.androidaps D/AndroidRuntime: Shutting down VM
02-23 10:34:29.743 20733-20733/info.nightscout.androidaps E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: info.nightscout.androidaps, PID: 20733
                                                                            java.lang.RuntimeException: Unable to resume activity {info.nightscout.androidaps/info.nightscout.androidaps.MainActivity}: java.lang.RuntimeException: Could not dispatch event: class info.nightscout.androidaps.events.EventFeatureRunning to handler [EventHandler public void info.nightscout.androidaps.plugins.PumpInsight.connector.Connector.onStatusEvent(info.nightscout.androidaps.events.EventFeatureRunning)]: Attempt to invoke virtual method 'void sugar.free.sightparser.handling.SightServiceConnector.connect()' on a null object reference
                                                                                at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
                                                                                at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
                                                                                at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                             Caused by: java.lang.RuntimeException: Could not dispatch event: class info.nightscout.androidaps.events.EventFeatureRunning to handler [EventHandler public void info.nightscout.androidaps.plugins.PumpInsight.connector.Connector.onStatusEvent(info.nightscout.androidaps.events.EventFeatureRunning)]: Attempt to invoke virtual method 'void sugar.free.sightparser.handling.SightServiceConnector.connect()' on a null object reference
                                                                                at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
                                                                                at com.squareup.otto.Bus.dispatch(Bus.java:387)
                                                                                at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
                                                                                at com.squareup.otto.Bus.post(Bus.java:337)
                                                                                at info.nightscout.androidaps.MainActivity.onResume(MainActivity.java:225)
                                                                                at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
                                                                                at android.app.Activity.performResume(Activity.java:7107)
                                                                                at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
                                                                                at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862) 
                                                                                at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                at android.os.Looper.loop(Looper.java:164) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
                                                                             Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void sugar.free.sightparser.handling.SightServiceConnector.connect()' on a null object reference
                                                                                at info.nightscout.androidaps.plugins.PumpInsight.connector.Connector.connectToPump(Connector.java:157)
                                                                                at info.nightscout.androidaps.plugins.PumpInsight.connector.Connector.onStatusEvent(Connector.java:505)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
                                                                                at com.squareup.otto.Bus.dispatch(Bus.java:385)
                                                                                at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368) 
                                                                                at com.squareup.otto.Bus.post(Bus.java:337) 
                                                                                at info.nightscout.androidaps.MainActivity.onResume(MainActivity.java:225) 
                                                                                at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355) 
                                                                                at android.app.Activity.performResume(Activity.java:7107) 
                                                                                at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556) 
                                                                                at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862) 
                                                                                at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                at android.os.Looper.loop(Looper.java:164) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
02-23 10:34:29.744 20733-20935/info.nightscout.androidaps E/INSIGHTPUMP: Staying connected thread expires: 2018-02-23 10:34:59

**Comment by jotomo** [comment] 2018-02-23 15:44
Will be fixed when #716 is merged.

**Comment by jotomo** [comment] 2018-03-01 15:51
@Rol71 Fixed via the above PR. Please close if works for you with `dev` now.

**Closed** 2018-03-01 22:21 UTC
