### ISSUE TITLE
Local Profile: UI config fails for non-consecutive PM entries

### ISSUE THREAD

**Issue by rustymonkey** [MilosKozak/AndroidAPS#1945] opened 2019-08-07 19:33 UTC
Adding entries to the local profile is not possible for PM entries that are > 1 hour after the last entry. I'm new to AAPS so I might be doing something stupid, but it looks like a UI issue.
 
Tested with 2.4 Alpha 2 (2019-08-02-13:17) on an S5 Mini running Android 6 as follows (both the pump and Android are configured with 12hour time):
1- Successfully tested the build using a nightscout-based profile with Medtronic 722
2- Open Config Builder and switch Profile from NSProfile to Local Profile
3- In Local Profile, enter 4 custom time/IC entries (12am:7.1, 6am:6.9, 10am:7.0, 11am:7.1) successfully
4- Attempt to add a 5th entry (4pm:7.0), but attempting to change the time for the 5th entry to 4pm 
--> time of the 3rd entry changes to "" !
--> time of the 5th entry changes to 12pm !
5- Attempt to change the 3rd "" entry --> UI doesn't respond

Further testing reveals that the following workaround works:
4- Add 5th, 6th, 7th, 8th,9th _consecutive_hourly_ entries (12pm:7.1, 1pm:7.1, 2pm:7.1, 3pm:7.1, 4pm:7.0)
But then attempting to add another non-consecutive entry (7pm:7.2) triggers the bug. i.e.
5- Enter 7pm:7.2 
--> 4pm:7.0 changes to "":7.0
-->new entry appears for 5pm (instead of 7pm as selected)

The problem occurs with IC, Basal, ISF, and Target configs in Local Profile.

**Comment by andyrozman** [comment] 2019-08-09 08:49
This should work with 24-hour entries, so I will have a look to see if I am not handling that... I know that I added this handling coming from MDT side, but maybe it doesn't work other way around. I will take a look and write here what I find out.

**Comment by andyrozman** [comment] 2019-08-12 16:33
@MilosKozak  But this seems to be UI problem not driver problem?

**Comment by MilosKozak** [comment] 2019-08-15 16:54
confirmed. it's a bug when AM PM is localized

**Comment by MilosKozak** [comment] 2019-08-22 18:36
fixed by https://github.com/MilosKozak/AndroidAPS/commit/d414b9b6511bdf9f03ef73f68bbe103d7f8e10b6

**Closed by MilosKozak** 2019-08-22 18:36 UTC

**Comment by rustymonkey** [comment] 2019-08-25 19:36
Verified the fix in 2.4 Alpha 5.
