### ISSUE TITLE
[Enhancement]: Alarm when battery is getting low

### ISSUE THREAD

**Issue by AlexD97** [MilosKozak/AndroidAPS#1486] opened 2018-10-03 16:01 UTC
Would it be possible to alarm the user when (DanaR) battery has only e.g. 2 bars left? #589 #1057

**Comment by schmitzn** [comment] 2018-10-03 21:05
Have a look at https://github.com/MilosKozak/AndroidAPS/pull/1107

**Comment by andyrozman** [comment] 2018-10-06 19:42
I think you can set that in Nightscout too (to get battery warnings)

**Comment by TebbeUbben** [comment] 2019-03-03 20:22
Duplicate of #1486

**Closed by TebbeUbben** 2019-03-03 20:22 UTC
Labels: enhancement
